# Source: cluster-api-aws/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cked59d1o-capi-aws
  namespace: cked59d1o
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cked59d1o-capi-aws
subjects:
- kind: ServiceAccount
  name: cked59d1o-capi-aws
